spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # AUTH SERVICE (NO JWT FILTER)
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        # FLIGHT SERVICE (JWT PROTECTED)
        - id: flight-service
          uri: lb://flight-service
          predicates:
            - Path=/flight/**
          filters:
            - JwtAuthenticationFilter

        # BOOKING SERVICE (JWT PROTECTED)
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/booking/**
          filters:
            - JwtAuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: my-super-secret-key-for-flight-booking-app
