spring:
  application:
    name: api-gateway

  cloud:
    gateway:

      # 🌐 GLOBAL CORS CONFIG
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      # 🚦 ROUTES
      routes:
        # AUTH SERVICE (PUBLIC)
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        # FLIGHT SERVICE (JWT PROTECTED)
        - id: flight-service
          uri: lb://flight-service
          predicates:
            - Path=/flight/**
          filters:
            - JwtAuthenticationFilter

        # SEAT SERVICE (JWT PROTECTED)
        - id: seat-service
          uri: lb://flight-service
          predicates:
            - Path=/seat/**
          filters:
            - JwtAuthenticationFilter

        # BOOKING SERVICE (JWT PROTECTED)
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/booking/**
          filters:
            - JwtAuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: my-super-secret-key-for-flight-booking-app
