spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: Nike2004$
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: my-super-secret-key-for-flight-booking-app
  expiration: 3600000   # 1 hour in milliseconds
